/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.videotutoria3_ejercicios;

import java.awt.Color;

/**
 *
 * @author javie
 */
public class DimensionesVentana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DimensionesVentana.class.getName());
    
    private static DimensionesVentana dv;

    /**
     * Creates new form DimensionesVentana
     */
    public DimensionesVentana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupResolucion = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        radioButon640 = new javax.swing.JRadioButton();
        radioButton800 = new javax.swing.JRadioButton();
        radioButton1024 = new javax.swing.JRadioButton();
        radioButton1920 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelTitulo.setText("Elije el tamaño de la ventana");

        buttonGroupResolucion.add(radioButon640);
        radioButon640.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioButon640.setText("640x480");
        radioButon640.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButon640ActionPerformed(evt);
            }
        });

        buttonGroupResolucion.add(radioButton800);
        radioButton800.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioButton800.setText("800x600");
        radioButton800.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton800ActionPerformed(evt);
            }
        });

        buttonGroupResolucion.add(radioButton1024);
        radioButton1024.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioButton1024.setText("1024x748");
        radioButton1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton1024ActionPerformed(evt);
            }
        });

        buttonGroupResolucion.add(radioButton1920);
        radioButton1920.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioButton1920.setText("1920x1080");
        radioButton1920.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton1920ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(radioButton1024, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(radioButton800, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButon640, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButton1920, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(218, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addGap(60, 60, 60)
                .addComponent(radioButon640)
                .addGap(18, 18, 18)
                .addComponent(radioButton800)
                .addGap(18, 18, 18)
                .addComponent(radioButton1024)
                .addGap(18, 18, 18)
                .addComponent(radioButton1920)
                .addGap(0, 132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButon640ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButon640ActionPerformed
        // TODO add your handling code here:
        dv.setSize(640, 480);
    }//GEN-LAST:event_radioButon640ActionPerformed

    private void radioButton800ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton800ActionPerformed
        // TODO add your handling code here:
        dv.setSize(800, 600);
    }//GEN-LAST:event_radioButton800ActionPerformed

    private void radioButton1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton1024ActionPerformed
        // TODO add your handling code here:
        dv.setSize(1024, 768);
    }//GEN-LAST:event_radioButton1024ActionPerformed

    private void radioButton1920ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton1920ActionPerformed
        // TODO add your handling code here:
        dv.setSize(1920, 1080);
    }//GEN-LAST:event_radioButton1920ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dv = new DimensionesVentana();
                dv.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupResolucion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JRadioButton radioButon640;
    private javax.swing.JRadioButton radioButton1024;
    private javax.swing.JRadioButton radioButton1920;
    private javax.swing.JRadioButton radioButton800;
    // End of variables declaration//GEN-END:variables
}
