/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.videotutoria3_ejercicios;

import java.awt.Color;

/**
 *
 * @author javie
 */
public class selectorRGB extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(selectorRGB.class.getName());

    /**
     * Creates new form selectorRGB
     */
    public selectorRGB() {
        initComponents();
        rellenarDesplegable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelSeleccion = new javax.swing.JPanel();
        comboBoxRojo = new javax.swing.JComboBox<>();
        comboBoxVerde = new javax.swing.JComboBox<>();
        comboBoxAzul = new javax.swing.JComboBox<>();
        labelRojo = new javax.swing.JLabel();
        labelVerde = new javax.swing.JLabel();
        labelAzul = new javax.swing.JLabel();
        botonPintar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelTitulo.setText("Selecciona un color RGB:");

        panelSeleccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comboBoxRojo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                comboBoxRojoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        labelRojo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelRojo.setText("Rojo:");

        labelVerde.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelVerde.setText("Verde:");

        labelAzul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelAzul.setText("Azul:");

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeleccionLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(labelRojo)
                        .addGap(55, 55, 55)
                        .addComponent(comboBoxRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSeleccionLayout.createSequentialGroup()
                            .addComponent(labelVerde)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelSeleccionLayout.createSequentialGroup()
                            .addComponent(labelAzul)
                            .addGap(57, 57, 57)
                            .addComponent(comboBoxAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 101, Short.MAX_VALUE))
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(comboBoxRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(comboBoxVerde, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelRojo)
                        .addGap(18, 18, 18)
                        .addComponent(labelVerde)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAzul)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(comboBoxAzul, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(69, 69, 69))
        );

        botonPintar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        botonPintar.setText("Pintar Botón");
        botonPintar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPintarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(botonPintar, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botonPintar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxRojoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboBoxRojoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxRojoAncestorMoved

    private void botonPintarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPintarActionPerformed
        // Obtenemos los valores seleccionados en los comboBox
        int colorRojo = Integer.parseInt(comboBoxRojo.getSelectedItem().toString());
        int colorVerde = Integer.parseInt(comboBoxVerde.getSelectedItem().toString());
        int colorAzul = Integer.parseInt(comboBoxAzul.getSelectedItem().toString());
        
        // Creamos una instancia de color en base a los valores de los comboBox RGB
        Color colorBoton = new Color(colorRojo, colorVerde, colorAzul);
        
        // Establecemos el color de fondo del boton con el color obtenido
        botonPintar.setBackground(colorBoton);
    }//GEN-LAST:event_botonPintarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new selectorRGB().setVisible(true));
    }

    private void rellenarDesplegable() {
        for (int i = 0; i <= 255; i++) {
            // Asignar los items a los ComboBox
            comboBoxRojo.addItem(Integer.toString(i));
            comboBoxVerde.addItem(Integer.toString(i));
            comboBoxAzul.addItem(Integer.toString(i));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPintar;
    private javax.swing.JComboBox<String> comboBoxAzul;
    private javax.swing.JComboBox<String> comboBoxRojo;
    private javax.swing.JComboBox<String> comboBoxVerde;
    private javax.swing.JLabel labelAzul;
    private javax.swing.JLabel labelRojo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVerde;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSeleccion;
    // End of variables declaration//GEN-END:variables
}
